### ISSUE TITLE
Enable admin to upload one or more than one custom fonts

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1629]
This ticket is to enable admin to upload one or more than one custom fonts from the graphical web administration interface, so that:
1. The platform make the fonts available as in-line resources like per default fonts (https://github.com/globaleaks/GlobaLeaks/commit/0d171bf6c755c0ba894a8380b8aa54bf4b89764a#commitcomment-17013297)
2. Make available and communicate on the web admin interface the name of the individual font resources that has been made available, so that the custom CSS developer will be able to reference it.

Maybe the low-level feature shall be done also for custom loaded "Images"

**Comment by evilaliv3** [comment]
I put here the status of the current research on this so that we can evaluate it for a very very long term, as a lot of requirements for this feature are missing and we definitely 

The only way to do this is:
1. generate serverside a file called custom-fonts.css to be loaded before of the custom css
2. the above file should contain simply rules following this format

```css
@font-face {
  font-family: 'CustomFont1;
  src: url('webfont.eot'); /* IE9 Compat Modes */
  src: url('webfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('webfont.woff2') format('woff2'), /* Super Modern Browsers */
       url('webfont.woff') format('woff'), /* Pretty Modern Browsers */
       url('webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('webfont.svg#svgFontName') format('svg'); /* Legacy iOS */
}
```

in order for the feature to be functional, each font (e.g. the above CustomFont1) should allow add different file formats  for each specified font (e.g. svg, woff, ttf) because each browser want's its fuckin' own.

**Comment by evilaliv3** [comment]
Worked on the customization of a still not disclosed user i'm analizing the fonts of their own website with: http://fontface.ninja/.

This is definitely a good browser plugin for doing this kind of job!

**Comment by evilaliv3** [comment]
![screenshot from 2016-04-10 12 11 36](https://cloud.githubusercontent.com/assets/217034/14409514/66a5e756-ff15-11e5-85e3-ff9f49de2705.png)

**Comment by evilaliv3** [comment]
As the specific adopter i'm working on is using ```fast.fonts.net``` i had to reverse the website, build a script for fetching the fonts.

The snippt used for doing that and the code used for the integration follows.

Here follows the bash script i used for retriving the fonts:
````bash
#!/bin/bash
## declare an array variable
declare -a arr_urls=(
  "url1_to_not_leak_the_adopter_name.eot"
  "url2_to_not_leak_the_adopter_name.eot"
  "url3_to_not_leak_the_adopter_name.eot"
  "url4_to_not_leak_the_adopter_name.eot"
  "url5_to_not_leak_the_adopter_name.eot"
  "url6_to_not_leak_the_adopter_name.eot"
  "url7_to_not_leak_the_adopter_name.eot"
  "url8_to_not_leak_the_adopter_name.eot"
)

declare -a arr_filenames=(
  "font1.eot"
  "font1.woff"
  "font1.ttf"
  "font1.svg"
  "font2.eot"
  "font2.woff"
  "font2.ttf"
  "font2.svg"
)


## now loop through the above array
for((i=0;i<${#arr_urls[@]};i++))
do
   wget "https://fast.fonts.net"${arr_urls[$i]} -O ${arr_filenames[$i]} --referer "https://fast.fonts.net"
done
```

Then the code has been integrated using the CSS described above.

**Comment by evilaliv3** [comment]
The final CSS code is the following;

I've removed the compatibility line for IE6-IE10 and this is the new code to be kept as reference:

```css
@font-face {
  font-family: 'CustomFont1';
  src: url('font1.eot'); /* IE9 Compat Modes */
  src: url('font1.woff') format('woff'), /* Pretty Modern Browsers */
       url('font1.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('font1.svg#svgFontName') format('svg'); /* Legacy iOS */
}

@font-face {
  font-family: 'CustomFont2';
  src: url('font1.eot'); /* IE9 Compat Modes */
  src: url('font1.woff') format('woff'), /* Pretty Modern Browsers */
       url('font1.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('font1.svg#svgFontName') format('svg'); /* Legacy iOS */
}

@font-face {
  font-family: 'CustomFont3';
  src: url('font1.eot'); /* IE9 Compat Modes */
  src: url('font1.woff') format('woff'), /* Pretty Modern Browsers */
       url('font1.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('font1.svg#svgFontName') format('svg'); /* Legacy iOS */
}

@font-face {
  font-family: 'CustomFont4';
  src: url('font1.eot'); /* IE9 Compat Modes */
  src: url('font1.woff') format('woff'), /* Pretty Modern Browsers */
       url('font1.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('font1.svg#svgFontName') format('svg'); /* Legacy iOS */
}
```
