### ISSUE TITLE
Long running promises involving status messages should always block the user from changing the page.

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1713]
Long running promises involving status messages should always block the user from changing the page or interrupting what is happening.

Right now the following interfaces affected:
- key generation page at the end of the wizard
- key generation page at the first login
- key update page at the end of the password change

**Comment by evilaliv3** [comment]
i'm addressing a proper refactor both on devel and on the browsercrypto branch in order to address this.

Basically i'm passing from a model where i've implemented this behaviour using the z-index tricky to a model that use the proper HTML5 CSS classes.

```css
.block-user-input {
  pointer-events: none;
  user-select: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
}
```

this can be applied to the root HTML element in this way:
```html
<div data-ng-class="{'block-user-input': showLoadingModal}">
  ...
</div>
```
