### ISSUE TITLE
Another twistd server is running, PID 1

### ISSUE THREAD

**Issue by robbitara** [globaleaks/GlobaLeaks#3957]
### What version of GlobaLeaks are you using?

4.14.0

### What browser(s) are you seeing the problem on?

Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hi, I installed Globaleaks with Docker on a Ubuntu VM running on VirtualBox.
The Windows machine that hosts the VM is scheduled to be shut down everyday at 2 AM e to automacally started at 5 AM.
The default docker-compose.yml works pretty good and ups the container correctly.
The problem is that every morning the globaleaks container was in a "boot loop", unable to start.
Running `docker ps` the globaleaks status was still on "Restarting", so I issued a `docker logs globaleaks` and found this message: 

> Another twistd server is running, PID 1

I found out that globaleaks writes a **globaleaks.pid** file on the mounted volume of the container to know that the application is running, so if that file is already there on startup, the container won't start.

This issue happened only on the scheduled restart of the Windows machine, because if I tried to shutdown the VM manually (running `"C:\Program Files\Oracle\VirtualBox\VboxManage.exe" controlvm "Ubuntu" acpipowerbutton`) the container stopped correctly.

So the only difference between the two shutdowns is the elapsed time since the `docker compose up -d` command.
I decided to look at the systemd logs running `journalctl -eu docker` and everyday at 2 AM I find this message:

> Container failed to exit within 10s of signal 15 - using the force

I don't know why the container takes more than 10 seconds to stop, so docker sends a SIGKILL signal to the container PID and the **globaleaks.pid** file remains dangling on the volume.

### Proposed solution

To solve this issue, I added the `stop_grace_period` configuration on the docker-compose.yml, in order to wait a greater amount of time before killing the container. This actually solved the issue.
My compose file now looks like this:

```
version: '3'

services:
  globaleaks:
    build: .
    restart: unless-stopped
    container_name: globaleaks
    network_mode: bridge
    volumes:
      - globaleaks:/var/globaleaks
    ports:
      - 443:8443
    stop_grace_period: 1m

volumes:
  globaleaks:
```
